version: "3.8"

# FIXME: running not from project root causes .env to not be loaded
services:
  web:
    container_name: "sport_web"
    build: ./ano
    ports:
      # local:docker
      - "7001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ano-go/uploads/:/app/uploads/
    depends_on:
      - backend
  backend:
    container_name: "sport_backend"
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_CONTAINER_NAME: ${DATABASE_CONTAINER_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
    build: ./ano-go
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./ano-go/:/app/
  db:
    container_name: "sport_db"
    build: ./database
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./database:/var/lib/mysql
