version: "3.8"

services:
  web:
    container_name: "sport_web"
    build: ./ano
    ports:
      # local:docker
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS}
  backend:
    container_name: "sport_backend"
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_CONTAINER_NAME: ${DATABASE_CONTAINER_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    build: ./ano-go
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./ano-go/:/app/
  db:
    container_name: "sport_db"
    build: ./database
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
