version: "3.8"

# Avoid running not from project root(directory where compose.yaml is stored) as it causes docker to silently fail .env file load
services:
  web:
    container_name: ${WEB_CONTAINER_NAME} 
    build: ./ano
    ports:
      # local:docker
      - "${LOCAL_PORT}:80"
    environment:
      BACKEND: ${BACKEND_CONTAINER_NAME}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ano-go/uploads/:/app/uploads/
    depends_on:
      - backend
  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_CONTAINER_NAME: ${DATABASE_CONTAINER_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
    build: ./ano-go
    depends_on:
      - db
    volumes:
      - ./ano-go/:/app/
  db:
    container_name: ${DATABASE_CONTAINER_NAME}
    build: ./database
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./database:/var/lib/mysql
