version: "3.8"

services:
  web:
    build: ./ano
    ports:
      # local:docker
      - "5000:80"
  backend:
    build: ./ano-go
    ports:
      - "8000:8000"
  db:
    build: ./database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Kikuri"
