# Avoid running not from project root(directory where compose.yaml is stored) as it causes docker to silently fail .env file load
services:
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build: ./ano
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      # local:docker
      - "${LOCAL_PORT}:80"
    environment:
      BACKEND: ${BACKEND_CONTAINER_NAME}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ano-go/uploads/:/app/uploads/
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: curl -f localhost:80
      start_interval: 1s

  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./ano-go
      dockerfile: Dockerfile.dev
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_CONTAINER_NAME: ${DATABASE_CONTAINER_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - ./ano-go/:/app/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -f localhost:8000/api/events?limit=0
      start_interval: 1s

  db:
    container_name: ${DATABASE_CONTAINER_NAME}
    build: ./database
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: mariadb --user=root --password='${DATABASE_ROOT_PASSWORD}' --execute='show databases;'
      start_interval: 1s

  cypress:
    container_name: ${CYPRESS_CONTAINER_NAME}
    build: ./cypress
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      CYPRESS_BASE_URL: ${BASE_URL}
      CYPRESS_ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./cypress/:/e2e/

volumes:
  database:
